# Copyright (c) 2017 Tim Heckman
# Use of this source code is governed by the MIT License that can be found in
# the LICENSE file at the root of this repository.

language: go
go:
- tip
- 1.11.x
- 1.12.x
env:
  - GO111MODULE=auto
sudo: false
notifications:
  email:
    on_success: never
    on_failure: always
before_install: make prebuild
install: dep ensure
